apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: digital-wallet-prod

resources:
  - namespace.yaml
  - ../../base
  - patches/postgres-retain.yaml
patches:
  - path: patches/postgres-resources.yaml
  - path: patches/postgres-storage.yaml
  

