apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: wallet
          image: ghcr.io/jisoz/wallet:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
