apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-config
data:
  config.yaml: |
    swaggerServer:
      enable: true
      port: 1314

    apiServer:
      enable: true
      port: 8082

    postgreSQL:
      host: postgres
      port: 5432
      user: postgres
      password: dev_password_123
      dbname: transaction
      sslmode: disable