apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - registry-secret.yaml
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - certificate.yaml
