apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wallet-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patches/postgres/*
  - path: patches/frontend/*
  - path: patches/wallet/*
  - path: patches/redis-storage.yaml 

