apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wallet-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patches/postgres/postgres-resources.yaml
  - path: patches/postgres/postgres-storage.yaml
  - path: patches/postgres/postgres-secret.yaml


  - path: patches/redis-storage.yaml

  - path: patches/frontend/deploy-front.yaml
  
  - path: patches/wallet/wallet-secret.yaml
  - path: patches/wallet/deploy-wallet.yaml
  - path: patches/wallet/configmap.yaml
  
  - path: patches/transaction/configmap.yaml
  - path: patches/transaction/deploy-transaction.yaml
  - path: patches/transaction/transaction-secret.yaml

