apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wallet-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patches/postgres-resources.yaml
  - path: patches/postgres-storage.yaml
  # - path: patches/redis-storage.yaml
  # - path: patches/deploy-wallet.yaml
  # - path: patches/deploy-front.yaml

